version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web: &app_base
    build: .
    command: /bin/sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      EDITOR: vim
      # RAILS_SERVE_STATIC_FILES: 1
    tty: true
    stdin_open: true
  webpacker:
    <<: *app_base
    command: /bin/sh -c "bundle install && rm -rf /app/public/packs && bin/webpack-dev-server"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      BUNDLE_APP_CONFIG: ./.bundle
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    tty: true
    stdin_open: true
    depends_on:
      - web
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
